version: '3.3'
services:
  mern:
    build:
      context: .
      dockerfile: mern.Dockerfile
    image: mern:get2know-react
    container_name: mern
    volumes:
      - type: bind
        source: ..
        target: /home/get2know-react/workspace
    ports:
      - "3000:3000"
